#!/bin/bash
if [[ $EUID -ne 0 ]];
then
	echo "You must be a root user" 2>&1 exit 1

else
	cd ~
	apt-get install -y nano
	apt-get install -y make
	apt-get install -y gcc-arm-none-eabi
	apt-get install -y gdb-arm-none-eabi
	apt-get install -y dh-autoreconf
	apt-get install -y libusb-1.0-0-dev
	apt-get install -y pkg-config
	apt-get install -y htop

	apt-get install -y libusb-dev
	apt-get install -y libftdi1
	apt-get install -y libftdi-dev

	apt-get install -y openocd

	git clone https://github.com/texane/stlink.git &&

	git clone https://github.com/mblythe86/stm32f3-discovery-basic-template.git
	
fi
