#!/bin/bash
if [[ $EUID -ne 0 ]];
then
	echo "You must be a root user" 2>&1 exit 1

else
	cd ~

	apt-get install -y gcc-avr
	apt-get install -y gdb-avr
	apt-get install -y dfu-programmer
	apt-get install -y avarice
	apt-get install -y avr-libc #You need atleast version 1.8.1+Atmel -> >= Ubuntu Vivid!

	cp /root/MCU_toolchain_Linux_Android/avr/build_avr /usr/bin/build_avr
	cp /root/MCU_toolchain_Linux_Android/avr/edit_avr /usr/bin/edit_avr
	cp /root/MCU_toolchain_Linux_Android/avr/cp_avr /usr/bin/cp_avr
	cp /root/MCU_toolchain_Linux_Android/avr/flash_avr /usr/bin/flash_avr

fi
