#!/bin/bash
if [[ $EUID -ne 0 ]];
then
	echo "You must be a root user" 2>&1 exit 1

else

	if hash st-flash 2>/dev/null;
	then
		echo >&2 "Stlink already installed, updating binaries."
		cp /root/public/build/build_stm32 /usr/bin/build_stm32
		cp /root/public/build/edit_stm32 /usr/bin/edit_stm32
		cp /root/public/build/gdb_stm32 /usr/bin/gdb_stm32
		cp /root/public/build/flash /usr/bin/flash
else
		cd ~/stlink
		./autogen.sh
		./configure
		make clean
		make &&
		cp /root/stlink/st-flash /usr/bin/st-flash
		cp /root/public/build/build_stm32 /usr/bin/build_stm32
		cp /root/public/build/edit_stm32 /usr/bin/edit_stm32
		cp /root/public/build/gdb_stm32 /usr/bin/gdb_stm32
		cp /root/public/build/flash /usr/bin/flash
	fi
fi
