#!/bin/bash
if [[ $EUID -ne 0 ]];
then
	echo "You must be a root user" 2>&1 exit 1

else
		cp /root/public/stm32/build_stm32 /usr/bin/build_stm32
		cp /root/public/stm32/edit_stm32 /usr/bin/edit_stm32
		cp /root/public/stm32/gdb_stm32 /usr/bin/gdb_stm32
		cp /root/public/stm32/flash_stm32 /usr/bin/flash_stm32
		cp /root/public/stm32/cp_stm32 /usr/bin/cp_stm32

	if hash st-flash 2>/dev/null;
	then
		echo >&2 "Stlink already installed, updating binaries."
	else

#Installing stlink
		cd ~/stlink
		./autogen.sh
		./configure
		make
		make install

#Making a new "Workspace" folder called Workspace.
		cp -avr /root/stm32f3-discovery-basic-template /root/public/stm32/Workspace
	fi
fi
