#!/bin/bash
cd /root/MCU_toolchain_Linux_Android/stm32vl/Workspace/
rm -f /root/MCU_toolchain_Linux_Android/stm32vl/Workspace/main.bin
make clean
make
arm-none-eabi-objcopy -O binary /root/MCU_toolchain_Linux_Android/stm32vl/Workspace/stm32vldiscovery-linux-template.elf /root/MCU_toolchain_Linux_Android/stm32vl/Workspace/main.bin
