#!/bin/bash
#Port = 4242
build_stm32
flash_stm32 &&

openocd -f /usr/share/openocd/scripts/interface/stlink-v2.cfg -f /usr/share/openocd/scripts/board/stm32f3discovery.cfg &
sleep 1 &&
arm-none-eabi-gdb /root/MCU_toolchain_Linux_Android/stm32/Workspace/main.elf --command=/root/MCU_toolchain_Linux_Android/stm32/gdb_commands
